SELECT 
	GAME_ID, 
	TEAM_ID, 
	TEAM_NAME,
	GAME_DATE,
	FG3M,
	FG3A,
	FG3A- FG3M AS FG3_MISSES,
	ROUND(FG3M *100.0/ FG3A , 2) AS FG3_PCT,
	CASE	
		WHEN GAME_ID = "0041700317"  THEN "X"
		END AS GAME_OF_INTEREST
	
FROM LEAGUE_GAME_LOGS
WHERE FG3_MISSES >= 37
ORDER BY FG3_MISSES DESC
